#!/usr/bin/env python3

import colors as c
from random import randint as r

def pick():
    return r(1,4)

def pick_color():
    num = pick()
    if num == (1):
        return(c.red + num)
    elif pick == (2):
        return(c.yellow + num)
    elif pick == (3):
        return(c.green + num)
    elif pick == (4):
        return(c.blue + num)

if __name__ == '__main__':
    print(c.clear + c.multi("Welcome to Simon!") + c.reset)
    num = pick()
    print(num)
