#!/usr/bin/env python3

import colors as c
from random import randint as r
import time

numbers = []

def pick():
    return r(1,4)

def pick_color():
    num = pick()

if __name__ == '__main__':
    print(c.clear + c.multi("Welcome to Simon!") + c.reset)
    print(c.multi("(press any key to continue)") + c.green)
    input()
    while True:
        new = pick()
        numbers.append(new)
        print(numbers)
        time.sleep(.5)
        print(c.clear)
        order = input("input number: ")
        answer = []
        for n in order:
            answer.append(int(n))
        if answer == numbers:
            print("AWESOME!")
        else:
            print("I am sorry you lost")
            
